export const orderRecords = [
  {
    id: "ORD-2607-0001",
    client: "Coleman Title Group",
    notary: "Bernadette W Hudlin",
    service: "Loan signing appointment",
    jurisdiction: "NC",
    appointment: "Jul 22 2026 at 10:30 AM ET",
    status: "Assignment Pending",
    documents: "6 uploaded documents",
    location: "210 Market Street, Raleigh, NC 27601",
  },
  {
    id: "ORD-2607-0002",
    client: "Grant & Ledger Law PLLC",
    notary: "Unassigned",
    service: "Electronic notarization",
    jurisdiction: "NC",
    appointment: "Jul 23 2026 at 2:00 PM ET",
    status: "Document Review",
    documents: "3 uploaded documents",
    location: "Remote document preparation",
  },
] as const;

export const orderOperationRecords = [
  {
    id: "ORD-2607-0001",
    client: "Coleman Title Group",
    clientProfile: "NSC-NC-2607-0001",
    clientContact: "Avery Coleman",
    clientEmail: "avery@example.com",
    notary: "Bernadette W Hudlin",
    notaryProfile: "NSN-NC-2607-0001",
    service: "Loan signing appointment",
    jurisdiction: "NC",
    appointment: "Jul 22 2026 at 10:30 AM ET",
    location: "210 Market Street, Raleigh, NC 27601",
    orderStatus: "Assignment Pending",
    assignmentStatus: "Notary acceptance required",
    documentStatus: "Malware scan complete",
    documentCount: "6 uploaded documents",
    validationStatus: "Validated release pending",
    ronStatus: "Not required",
    billingStatus: "Invoice Pending",
    payableStatus: "Payable Restricted",
    communicationStatus: "Client notice failed",
    owner: "Admin",
    risk: "Financial hold",
    nextAction: "Confirm notary acceptance, retry client notice, and hold invoice release until assignment is active.",
  },
  {
    id: "ORD-2607-0002",
    client: "Grant & Ledger Law PLLC",
    clientProfile: "NSC pending approval",
    clientContact: "Marisol Grant",
    clientEmail: "marisol@example.com",
    notary: "Unassigned",
    notaryProfile: "Not assigned",
    service: "Electronic notarization",
    jurisdiction: "NC",
    appointment: "Jul 23 2026 at 2:00 PM ET",
    location: "Remote document preparation",
    orderStatus: "Document Review",
    assignmentStatus: "Assignment required",
    documentStatus: "Replacement document requested",
    documentCount: "3 uploaded documents",
    validationStatus: "Restricted document review",
    ronStatus: "Restricted until authorization confirmed",
    billingStatus: "Billing Locked",
    payableStatus: "No payable until assignment",
    communicationStatus: "Client correction open",
    owner: "GenAdmin003",
    risk: "Assignment and RON review",
    nextAction: "Request missing documents, confirm client authority, and route assignment after validation clears.",
  },
  {
    id: "ORD-2607-0003",
    client: "Oak City Home Buyer",
    clientProfile: "Consumer intake",
    clientContact: "Morgan Price",
    clientEmail: "morgan@example.com",
    notary: "Bernadette W Hudlin",
    notaryProfile: "NSN-NC-2607-0001",
    service: "Traditional mobile notarization",
    jurisdiction: "NC",
    appointment: "Jul 24 2026 at 6:00 PM ET",
    location: "540 Pinecrest Road, Durham, NC 27701",
    orderStatus: "Ready for confirmation",
    assignmentStatus: "Assigned; notary confirmation pending",
    documentStatus: "No document package required",
    documentCount: "0 uploaded documents",
    validationStatus: "Identity check required at appointment",
    ronStatus: "Not required",
    billingStatus: "Payment method review",
    payableStatus: "Payable held until completion",
    communicationStatus: "Confirmation queued",
    owner: "GenAdmin001",
    risk: "Standard",
    nextAction: "Confirm appointment details and keep completion controls locked until notary certificate is returned.",
  },
] as const;

export const notaryAssignmentRecords = orderOperationRecords.filter(
  (order) => order.notary !== "Unassigned",
);

export const orderLifecycleRecords = [
  {
    orderId: "ORD-2607-0001",
    stage: "Intake",
    status: "Complete",
    owner: "Client",
    authority: "Client authorized user",
    timestamp: "Jul 18 2026 at 4:10 PM ET",
    evidence: "Order request and client profile authority",
    nextAction: "Retain intake record with order case file.",
  },
  {
    orderId: "ORD-2607-0001",
    stage: "Document validation",
    status: "Release pending",
    owner: "Admin",
    authority: "Administrator or Super Admin",
    timestamp: "Jul 18 2026 at 4:20 PM ET",
    evidence: "seller-closing-package.pdf and borrower-identification-copy.pdf",
    nextAction: "Release validated documents after access classification is confirmed.",
  },
  {
    orderId: "ORD-2607-0001",
    stage: "Notary assignment",
    status: "Acceptance required",
    owner: "Admin",
    authority: "Administrator or Super Admin",
    timestamp: "Jul 18 2026 at 4:24 PM ET",
    evidence: "NSN-NC-2607-0001 assignment eligibility",
    nextAction: "Confirm notary acceptance before appointment confirmation.",
  },
  {
    orderId: "ORD-2607-0001",
    stage: "Appointment confirmation",
    status: "Pending",
    owner: "GenAdmin001",
    authority: "Authorized staff",
    timestamp: "Jul 18 2026 at 4:28 PM ET",
    evidence: "Jul 22 2026 at 10:30 AM ET appointment window",
    nextAction: "Confirm client, signer, notary, location, and document package availability.",
  },
  {
    orderId: "ORD-2607-0001",
    stage: "Completion package",
    status: "Locked",
    owner: "Assigned notary",
    authority: "Assigned notary and staff review",
    timestamp: "Pending",
    evidence: "Notarial certificate, completion notes, return documents",
    nextAction: "Unlock after appointment is completed and package is uploaded.",
  },
  {
    orderId: "ORD-2607-0001",
    stage: "Closeout",
    status: "Locked",
    owner: "Admin",
    authority: "Administrator or Super Admin",
    timestamp: "Pending",
    evidence: "Invoice, payable, delivery confirmation, and audit receipts",
    nextAction: "Close only after documents, billing, payable, and communications are complete.",
  },
  {
    orderId: "ORD-2607-0002",
    stage: "Intake",
    status: "Complete",
    owner: "Client",
    authority: "Client authorized user",
    timestamp: "Jul 18 2026 at 4:35 PM ET",
    evidence: "Electronic notarization request",
    nextAction: "Confirm client authority and service eligibility.",
  },
  {
    orderId: "ORD-2607-0002",
    stage: "Document validation",
    status: "Replacement requested",
    owner: "GenAdmin003",
    authority: "Authorized staff",
    timestamp: "Jul 18 2026 at 4:42 PM ET",
    evidence: "Restricted document review",
    nextAction: "Wait for replacement upload and malware validation.",
  },
  {
    orderId: "ORD-2607-0002",
    stage: "Notary assignment",
    status: "Unassigned",
    owner: "Admin",
    authority: "Administrator or Super Admin",
    timestamp: "Pending",
    evidence: "RON authority and notary availability required",
    nextAction: "Queue notary assignment after document and RON controls clear.",
  },
  {
    orderId: "ORD-2607-0003",
    stage: "Intake",
    status: "Complete",
    owner: "Client",
    authority: "Consumer intake",
    timestamp: "Jul 18 2026 at 4:50 PM ET",
    evidence: "Mobile notarization request",
    nextAction: "Confirm appointment and signer identity requirements.",
  },
  {
    orderId: "ORD-2607-0003",
    stage: "Appointment confirmation",
    status: "Ready",
    owner: "GenAdmin001",
    authority: "Authorized staff",
    timestamp: "Jul 18 2026 at 4:54 PM ET",
    evidence: "Jul 24 2026 at 6:00 PM ET appointment window",
    nextAction: "Confirm appointment details with client and assigned notary.",
  },
] as const;

export const orderCompletionRecords = [
  {
    orderId: "ORD-2607-0001",
    requirement: "Notary acceptance",
    status: "Required",
    evidence: "Assigned notary acceptance receipt",
    owner: "Admin",
  },
  {
    orderId: "ORD-2607-0001",
    requirement: "Appointment confirmation",
    status: "Pending",
    evidence: "Client and notary confirmation notice",
    owner: "GenAdmin001",
  },
  {
    orderId: "ORD-2607-0001",
    requirement: "Completion package",
    status: "Locked",
    evidence: "Executed documents, notarial certificate, and completion notes",
    owner: "Assigned notary",
  },
  {
    orderId: "ORD-2607-0001",
    requirement: "Invoice release",
    status: "Held",
    evidence: "Client invoice and ledger report",
    owner: "Administrator",
  },
  {
    orderId: "ORD-2607-0001",
    requirement: "Notary payable",
    status: "Restricted",
    evidence: "W-9 and payable activation control",
    owner: "Administrator or Super Admin",
  },
  {
    orderId: "ORD-2607-0001",
    requirement: "Closeout audit",
    status: "Locked",
    evidence: "Command receipts, delivery log, and financial controls",
    owner: "Super Admin",
  },
] as const;

export const documentRecords = [
  {
    id: "DOC-2607-0001",
    evidenceId: "DOC-2607-0001",
    fileName: "seller-closing-package.pdf",
    order: "ORD-2607-0001",
    custody: "Client uploaded",
    status: "Malware scan complete",
    access: "Client, assigned notary, staff",
    received: "Jul 18 2026 at 4:15 PM ET",
  },
  {
    id: "DOC-2607-0002",
    evidenceId: "DOC-2607-0002",
    fileName: "borrower-identification-copy.pdf",
    order: "ORD-2607-0001",
    custody: "Restricted identity document",
    status: "Restricted staff view",
    access: "Staff and assigned notary only",
    received: "Jul 18 2026 at 4:18 PM ET",
  },
] as const;

export const authorizedUsers = [
  {
    name: "Avery Coleman",
    email: "avery@example.com",
    role: "Client Account Administrator",
    status: "MFA required",
    permissions: "Orders, documents, user invitations",
  },
  {
    name: "Renee Walton",
    email: "renee@example.com",
    role: "Order Submitter",
    status: "Invitation pending",
    permissions: "Create orders, upload documents",
  },
] as const;

export const notificationRecords = [
  {
    id: "NTF-2607-0001",
    relatedRecord: "NSR-1001",
    recipientName: "Bernadette W Hudlin",
    recipient: "hudlinbe@example.com",
    channel: "Email",
    purpose: "Profile approval notice",
    status: "Queued after final approval",
    consent: "Email permitted",
    trigger: "Admin/Super Admin final approval",
    owner: "System",
    timestamp: "Jul 18 2026 at 5:00 PM ET",
    nextAction: "Send after profile activation is persisted.",
  },
  {
    id: "NTF-2607-0002",
    relatedRecord: "NSR-1001",
    recipientName: "Bernadette W Hudlin",
    recipient: "555-123-4567",
    channel: "Phone message",
    purpose: "Profile approval notice",
    status: "Requires recorded consent",
    consent: "Phone consent required",
    trigger: "Admin/Super Admin final approval",
    owner: "Operations",
    timestamp: "Jul 18 2026 at 5:01 PM ET",
    nextAction: "Verify communication consent before delivery.",
  },
  {
    id: "NTF-2607-0003",
    relatedRecord: "NSR-1002",
    recipientName: "Avery Coleman",
    recipient: "avery@example.com",
    channel: "Email",
    purpose: "Profile correction notice",
    status: "Sent",
    consent: "Email permitted",
    trigger: "GenAdmin correction request",
    owner: "GenAdmin002",
    timestamp: "Jul 18 2026 at 3:42 PM ET",
    nextAction: "Await corrected billing authorization response.",
  },
  {
    id: "NTF-2607-0004",
    relatedRecord: "NSR-1004",
    recipientName: "Super Admin and Administrator",
    recipient: "superadmin@notarix.live",
    channel: "Email",
    purpose: "Elevated approval ready",
    status: "Queued",
    consent: "Internal staff notice",
    trigger: "GenAdmin verification complete",
    owner: "GenAdmin002",
    timestamp: "Jul 11 2026 at 2:16 PM ET",
    nextAction: "Review final approval and financial controls.",
  },
  {
    id: "NTF-2607-0005",
    relatedRecord: "ORD-2607-0001",
    recipientName: "Coleman Title Group",
    recipient: "closings@example.com",
    channel: "Email",
    purpose: "Order document notice",
    status: "Failed",
    consent: "Email permitted",
    trigger: "Document upload event",
    owner: "System",
    timestamp: "Jul 18 2026 at 4:22 PM ET",
    nextAction: "Retry delivery and escalate if failure repeats.",
  },
  {
    id: "NTF-2607-0006",
    relatedRecord: "NSR-1001",
    recipientName: "Bernadette W Hudlin",
    recipient: "hudlinbe@example.com",
    channel: "Email",
    purpose: "Credential expiration reminder",
    status: "Scheduled",
    consent: "Email permitted",
    trigger: "Credential monitor",
    owner: "System",
    timestamp: "Oct 02 2026 at 9:00 AM ET",
    nextAction: "Send 90-day commission expiration reminder.",
  },
] as const;

export const credentialMonitorRecords = [
  {
    id: "CRD-2607-0001",
    profile: "NSN-NC-2607-0001",
    requestId: "NSR-1001",
    owner: "Bernadette W Hudlin",
    ownerType: "Notary",
    credential: "Notary commission",
    evidenceId: "EV-NOTARY-COMMISSION-CERTIFICATE",
    evidence: "notary-commission-certificate.pdf",
    expiration: "Dec 31 2026",
    renewalWindow: "90-day renewal window opens Oct 02 2026",
    status: "Active",
    reminder: "First reminder scheduled for Oct 02 2026 at 9:00 AM ET",
    notificationId: "NTF-2607-0006",
    eligibilityImpact: "Assignment eligibility remains active until expiration.",
    authority: "GenAdmin review; Admin/Super Admin override only",
    nextAction: "Monitor replacement commission certificate before expiration.",
  },
  {
    id: "CRD-2607-0002",
    profile: "NSN-NC-2607-0001",
    requestId: "NSR-1001",
    owner: "Bernadette W Hudlin",
    ownerType: "Notary",
    credential: "E&O insurance",
    evidenceId: "EV-EO-INSURANCE-DECLARATION",
    evidence: "eo-insurance-declaration-page.pdf",
    expiration: "Nov 30 2026",
    renewalWindow: "90-day renewal window opens Sep 01 2026",
    status: "Renewal due",
    reminder: "Follow-up reminders every 15 days after first notice",
    notificationId: "Pending",
    eligibilityImpact: "Loan signing assignment eligibility is blocked if coverage expires.",
    authority: "GenAdmin review; Admin/Super Admin override only",
    nextAction: "Request updated declaration page and confirm coverage amount.",
  },
  {
    id: "CRD-2607-0003",
    profile: "NSR-1003",
    requestId: "NSR-1003",
    owner: "Jordan Ellis",
    ownerType: "Notary",
    credential: "RON digital certificate",
    evidenceId: "EV-RON-DIGITAL-CERTIFICATE",
    evidence: "ron-digital-certificate-record.pdf",
    expiration: "Oct 15 2026",
    renewalWindow: "30-day elevated RON renewal window opens Sep 15 2026",
    status: "Elevated review",
    reminder: "Weekly reminders beginning 30 days before expiration",
    notificationId: "Pending",
    eligibilityImpact: "RON assignment eligibility restricted until renewed certificate is verified.",
    authority: "Administrator or Super Admin",
    nextAction: "Escalate renewed digital certificate and RON authorization evidence.",
  },
  {
    id: "CRD-2607-0004",
    profile: "NSR-1002",
    requestId: "NSR-1002",
    owner: "Coleman Title Group",
    ownerType: "Client",
    credential: "Client billing authorization",
    evidenceId: "EV-CLIENT-BILLING-AUTH",
    evidence: "client-billing-authorization.pdf",
    expiration: "Annual review Dec 31 2026",
    renewalWindow: "Client authority review opens Nov 01 2026",
    status: "Restricted",
    reminder: "Billing authority reminder held until elevated approval is recorded",
    notificationId: "Pending",
    eligibilityImpact: "Billing permissions remain restricted until elevated financial approval.",
    authority: "Administrator or Super Admin",
    nextAction: "Confirm authorized representative and billing authority before renewal.",
  },
] as const;

export const supportThreads = [
  {
    id: "MSG-2607-0001",
    subject: "Correction request for billing authorization",
    participant: "Coleman Title Group",
    owner: "GenAdmin002",
    status: "Awaiting client response",
    lastActivity: "Jul 18 2026 at 3:42 PM ET",
  },
  {
    id: "MSG-2607-0002",
    subject: "RON authorization evidence question",
    participant: "Jordan Ellis",
    owner: "GenAdmin005",
    status: "Escalated",
    lastActivity: "Jul 18 2026 at 4:05 PM ET",
  },
] as const;

export const financialControlRecords = [
  {
    id: "FIN-2607-0001",
    profile: "NSR-1001",
    profileType: "Notary",
    owner: "Bernadette W Hudlin",
    organization: "DaWaHu Collective, LLC",
    control: "W-9 and payable activation",
    evidenceId: "EV-W9-FORM",
    evidence: "completed-w-9-form.pdf",
    status: "Restricted",
    reviewer: "GenAdmin004",
    authority: "Administrator or Super Admin",
    lastUpdated: "Jul 10 2026 at 11:55 AM ET",
    decision: "General Admin may review completion status but cannot approve payable activation.",
  },
  {
    id: "FIN-2607-0002",
    profile: "NSR-1002",
    profileType: "Client",
    owner: "Avery Coleman",
    organization: "Coleman Title Group",
    control: "Client billing authorization",
    evidenceId: "EV-CLIENT-BILLING-AUTH",
    evidence: "client-billing-authorization.pdf",
    status: "Restricted",
    reviewer: "Admin approval",
    authority: "Administrator or Super Admin",
    lastUpdated: "Jul 10 2026 at 12:35 PM ET",
    decision: "Invoice terms and billing permissions remain disabled until elevated approval is recorded.",
  },
  {
    id: "FIN-2607-0003",
    profile: "NSR-1004",
    profileType: "Client",
    owner: "Marisol Grant",
    organization: "Grant & Ledger Law PLLC",
    control: "Invoice terms and order billing limits",
    evidenceId: "EV-CLIENT-BILLING-AUTH",
    evidence: "client-billing-authorization.pdf",
    status: "Ready for Elevated Approval",
    reviewer: "GenAdmin002",
    authority: "Administrator or Super Admin",
    lastUpdated: "Jul 11 2026 at 2:15 PM ET",
    decision: "Financial activation should occur only as part of final elevated approval.",
  },
  {
    id: "FIN-2607-0004",
    profile: "ORD-2607-0001",
    profileType: "Order",
    owner: "Coleman Title Group",
    organization: "Coleman Title Group",
    control: "Payment ledger correction",
    evidenceId: "DOC-2607-0001",
    evidence: "seller-closing-package.pdf",
    status: "Locked",
    reviewer: "Super Admin",
    authority: "Super Admin",
    lastUpdated: "Jul 18 2026 at 4:20 PM ET",
    decision: "Ledger corrections require restricted audit review and cannot be completed by General Admin.",
  },
] as const;

export const auditReportRecords = [
  {
    id: "AUD-2607-0001",
    area: "Profile verification",
    relatedRecord: "NSR-1001",
    actor: "GenAdmin001",
    role: "General Admin",
    event: "Identity section marked verified after provider evidence review.",
    risk: "Controlled",
    authority: "General Admin verification",
    timestamp: "Jul 10 2026 at 10:34 AM ET",
    retention: "Retain with profile verification audit report",
    nextAction: "Await remaining profile sections before elevated approval.",
  },
  {
    id: "AUD-2607-0002",
    area: "Evidence access",
    relatedRecord: "EV-W9-FORM",
    actor: "GenAdmin004",
    role: "General Admin",
    event: "Restricted W-9 evidence opened for payable completion review.",
    risk: "Restricted",
    authority: "Financial evidence access logged",
    timestamp: "Jul 18 2026 at 5:00 PM ET",
    retention: "Retain under tax onboarding and payable control policy",
    nextAction: "Administrator or Super Admin must approve payable activation.",
  },
  {
    id: "AUD-2607-0003",
    area: "Final approval",
    relatedRecord: "NSR-1004",
    actor: "Admin",
    role: "Administrator",
    event: "Client profile final approval generated NSC-NC-2607-0001.",
    risk: "Elevated",
    authority: "Administrator or Super Admin approval",
    timestamp: "Jul 18 2026 at 5:00 PM ET",
    retention: "Retain permanently with approved client profile number history",
    nextAction: "Monitor notification delivery and client billing restrictions.",
  },
  {
    id: "AUD-2607-0004",
    area: "Notification delivery",
    relatedRecord: "NTF-2607-0005",
    actor: "System",
    role: "System",
    event: "Order document notice failed delivery to client recipient.",
    risk: "Attention",
    authority: "Delivery retry or suppression requires audit note",
    timestamp: "Jul 18 2026 at 4:22 PM ET",
    retention: "Retain with order communication history",
    nextAction: "Retry delivery and escalate if failure repeats.",
  },
  {
    id: "AUD-2607-0005",
    area: "RON restriction",
    relatedRecord: "CRD-2607-0003",
    actor: "GenAdmin005",
    role: "General Admin",
    event: "RON digital certificate renewal moved to elevated review.",
    risk: "Restricted",
    authority: "Administrator or Super Admin required",
    timestamp: "Jul 18 2026 at 5:08 PM ET",
    retention: "Retain with RON authorization and credential renewal report",
    nextAction: "Keep RON eligibility restricted until renewed evidence is verified.",
  },
  {
    id: "AUD-2607-0006",
    area: "Financial control",
    relatedRecord: "FIN-2607-0004",
    actor: "Super Admin",
    role: "SuperAdmin",
    event: "Payment ledger correction remains locked pending restricted audit review.",
    risk: "High",
    authority: "Super Admin only",
    timestamp: "Jul 18 2026 at 4:20 PM ET",
    retention: "Retain permanently with payment ledger correction history",
    nextAction: "Review ledger evidence before releasing any correction.",
  },
] as const;

export const paymentLedgerRecords = [
  {
    id: "LED-2607-0001",
    relatedRecord: "ORD-2607-0001",
    party: "Coleman Title Group",
    profile: "NSC-NC-2607-0001",
    ledgerType: "Client invoice",
    amount: "$275.00",
    status: "Invoice Pending",
    control: "Document package received; assignment still pending",
    authority: "Administrator review",
    evidenceId: "DOC-2607-0001",
    posted: "Jul 18 2026 at 4:20 PM ET",
    nextAction: "Hold invoice release until order assignment is confirmed.",
  },
  {
    id: "LED-2607-0002",
    relatedRecord: "NSR-1001",
    party: "Bernadette W Hudlin",
    profile: "NSN pending approval",
    ledgerType: "Notary payable",
    amount: "$150.00",
    status: "Payable Restricted",
    control: "W-9 and payable activation pending elevated approval",
    authority: "Administrator or Super Admin",
    evidenceId: "EV-W9-FORM",
    posted: "Jul 10 2026 at 11:55 AM ET",
    nextAction: "Do not release payable until approved profile number and W-9 control are active.",
  },
  {
    id: "LED-2607-0003",
    relatedRecord: "NSR-1002",
    party: "Coleman Title Group",
    profile: "NSC pending approval",
    ledgerType: "Billing authorization",
    amount: "Terms restricted",
    status: "Billing Locked",
    control: "Client billing authorization requires elevated approval",
    authority: "Administrator or Super Admin",
    evidenceId: "EV-CLIENT-BILLING-AUTH",
    posted: "Jul 10 2026 at 12:35 PM ET",
    nextAction: "Confirm authorized representative and invoice terms before activation.",
  },
  {
    id: "LED-2607-0004",
    relatedRecord: "ORD-2607-0001",
    party: "Coleman Title Group",
    profile: "NSC-NC-2607-0001",
    ledgerType: "Ledger correction",
    amount: "$25.00 adjustment",
    status: "Correction Locked",
    control: "Payment ledger correction cannot be completed by General Admin",
    authority: "Super Admin",
    evidenceId: "DOC-2607-0001",
    posted: "Jul 18 2026 at 4:20 PM ET",
    nextAction: "Super Admin must review restricted audit report before correction.",
  },
] as const;

export const retentionPolicyRecords = [
  {
    id: "RET-2607-0001",
    category: "Profile records",
    relatedWorkflow: "Profile verification",
    relatedRecord: "NSR-1001",
    retentionPeriod: "Retain while profile is active plus required audit period",
    status: "Active retention",
    holdStatus: "No hold",
    deletionEligibility: "Not eligible",
    authority: "Administrator or Super Admin",
    lastReviewed: "Jul 18 2026 at 5:10 PM ET",
    nextAction: "Review after profile closure or regulatory retention window.",
  },
  {
    id: "RET-2607-0002",
    category: "Identity proofing records",
    relatedWorkflow: "Evidence and provider results",
    relatedRecord: "EV-IDENTITY-DOCUMENT-ANALYSIS",
    retentionPeriod: "Retain with identity verification and restricted audit file",
    status: "Restricted retention",
    holdStatus: "Audit hold recommended",
    deletionEligibility: "Not eligible",
    authority: "Super Admin",
    lastReviewed: "Jul 18 2026 at 5:12 PM ET",
    nextAction: "Place retention hold before any identity evidence dispute review.",
  },
  {
    id: "RET-2607-0003",
    category: "Order documents",
    relatedWorkflow: "Order file",
    relatedRecord: "ORD-2607-0001",
    retentionPeriod: "Retain with order file according to document retention policy",
    status: "Controlled retention",
    holdStatus: "No hold",
    deletionEligibility: "Review after retention period",
    authority: "Administrator or Super Admin",
    lastReviewed: "Jul 18 2026 at 4:22 PM ET",
    nextAction: "Keep order documents linked to order audit history.",
  },
  {
    id: "RET-2607-0004",
    category: "W-9 and payable records",
    relatedWorkflow: "Financial controls",
    relatedRecord: "EV-W9-FORM",
    retentionPeriod: "Retain under tax onboarding and payable control policy",
    status: "Restricted retention",
    holdStatus: "Financial hold",
    deletionEligibility: "Not eligible",
    authority: "Super Admin",
    lastReviewed: "Jul 18 2026 at 5:14 PM ET",
    nextAction: "Do not release while payable activation or tax review remains restricted.",
  },
  {
    id: "RET-2607-0005",
    category: "Command receipts",
    relatedWorkflow: "Command center",
    relatedRecord: "CMD-2607",
    retentionPeriod: "Retain with append-only operational audit history",
    status: "Append-only",
    holdStatus: "Permanent audit retention",
    deletionEligibility: "Never eligible for destructive deletion",
    authority: "Super Admin",
    lastReviewed: "Jul 18 2026 at 5:15 PM ET",
    nextAction: "Preserve completed and blocked command receipts.",
  },
] as const;

export const systemHealthRecords = [
  {
    id: "SYS-2607-0001",
    service: "Database backup",
    category: "Backup and recovery",
    status: "Backup current",
    environment: "Production-ready binding pending",
    lastChecked: "Jul 18 2026 at 5:20 PM ET",
    recoveryPoint: "15-minute target after production database binding",
    authority: "Administrator or Super Admin",
    nextAction: "Verify backup restore procedure before production launch.",
  },
  {
    id: "SYS-2607-0002",
    service: "Encrypted evidence storage",
    category: "R2 object storage",
    status: "Provider binding required",
    environment: "Production storage pending",
    lastChecked: "Jul 18 2026 at 5:21 PM ET",
    recoveryPoint: "Object metadata retained in D1; file bytes require R2 backup policy",
    authority: "Super Admin",
    nextAction: "Connect encrypted storage, signed URLs, retention, and malware scanning.",
  },
  {
    id: "SYS-2607-0003",
    service: "Notification provider",
    category: "Email, phone, and SMS callbacks",
    status: "Callback integration pending",
    environment: "Provider credentials not configured",
    lastChecked: "Jul 18 2026 at 5:22 PM ET",
    recoveryPoint: "Delivery logs retained; provider callback replay required",
    authority: "Administrator or Super Admin",
    nextAction: "Configure delivery callbacks and retry queue before launch.",
  },
  {
    id: "SYS-2607-0004",
    service: "Identity provider MFA/passkeys",
    category: "Authentication and RBAC",
    status: "Production IdP required",
    environment: "Local preview authentication",
    lastChecked: "Jul 18 2026 at 5:23 PM ET",
    recoveryPoint: "Emergency access must require Super Admin approval",
    authority: "Super Admin",
    nextAction: "Bind production IdP with MFA, passkeys, device controls, and role claims.",
  },
  {
    id: "SYS-2607-0005",
    service: "Malware scanning service",
    category: "Document validation",
    status: "Provider integration pending",
    environment: "Validation records modeled",
    lastChecked: "Jul 18 2026 at 5:24 PM ET",
    recoveryPoint: "Quarantine records retained with evidence validation queue",
    authority: "Administrator or Super Admin",
    nextAction: "Connect scanner results to document validation release controls.",
  },
] as const;

export const accessControlRecords = [
  {
    id: "IAM-2607-0001",
    staffUser: "GenAdmin001",
    email: "genadmin001@notarix.live",
    role: "GenAdmin",
    mfaStatus: "MFA enrolled",
    passkeyStatus: "Passkey pending production IdP",
    deviceStatus: "Approved staff device required",
    sessionStatus: "Active preview session",
    accessReview: "Quarterly review due Sep 30 2026",
    restrictedRoutes: "No final approval, financial activation, or Super Admin audit reports",
    lastReviewed: "Jul 18 2026 at 5:26 PM ET",
    nextAction: "Confirm production identity-provider role claim before launch.",
  },
  {
    id: "IAM-2607-0002",
    staffUser: "Admin",
    email: "admin@notarix.live",
    role: "Admin",
    mfaStatus: "MFA required",
    passkeyStatus: "Passkey enrollment required",
    deviceStatus: "Device compliance review required",
    sessionStatus: "Elevated session review",
    accessReview: "Access review open",
    restrictedRoutes: "No Super Admin audit retention release or break-glass approval",
    lastReviewed: "Jul 18 2026 at 5:27 PM ET",
    nextAction: "Require passkey enrollment and device attestation before production access.",
  },
  {
    id: "IAM-2607-0003",
    staffUser: "Super Admin",
    email: "superadmin@notarix.live",
    role: "SuperAdmin",
    mfaStatus: "Phishing-resistant MFA required",
    passkeyStatus: "Passkey required",
    deviceStatus: "Managed device required",
    sessionStatus: "Break-glass disabled",
    accessReview: "Monthly executive review",
    restrictedRoutes: "All restricted controls visible; destructive actions still require receipt",
    lastReviewed: "Jul 18 2026 at 5:28 PM ET",
    nextAction: "Bind production IdP policy, session lifetime, and emergency access approval.",
  },
  {
    id: "IAM-2607-0004",
    staffUser: "Support Review",
    email: "support-review@notarix.live",
    role: "Support",
    mfaStatus: "MFA required",
    passkeyStatus: "No passkey enrolled",
    deviceStatus: "Unapproved device",
    sessionStatus: "Suspension recommended",
    accessReview: "Exception review required",
    restrictedRoutes: "No evidence, financial, audit, or profile approval access",
    lastReviewed: "Jul 18 2026 at 5:29 PM ET",
    nextAction: "Suspend session until role and device controls are approved.",
  },
] as const;

export const providerIntegrationRecords = [
  {
    id: "INT-2607-0001",
    provider: "Identity provider",
    serviceArea: "MFA, passkeys, RBAC claims",
    status: "Production binding required",
    environment: "Local preview only",
    dataAccess: "Staff identity, role claims, device posture",
    complianceControl: "MFA, phishing-resistant passkeys, least privilege, session policy",
    lastChecked: "Jul 18 2026 at 5:30 PM ET",
    owner: "Super Admin",
    nextAction: "Connect production IdP and enforce role claims on protected routes.",
  },
  {
    id: "INT-2607-0002",
    provider: "Email and SMS delivery",
    serviceArea: "Notifications and phone messages",
    status: "Callback integration pending",
    environment: "Provider credentials not configured",
    dataAccess: "Recipient contact, consent, notice purpose, delivery status",
    complianceControl: "Consent capture, retry limits, delivery callbacks, suppression records",
    lastChecked: "Jul 18 2026 at 5:31 PM ET",
    owner: "Administrator",
    nextAction: "Configure delivery provider callbacks and consent-aware retry handling.",
  },
  {
    id: "INT-2607-0003",
    provider: "Encrypted file storage",
    serviceArea: "Evidence and order documents",
    status: "Storage binding pending",
    environment: "R2 production binding required",
    dataAccess: "Evidence metadata, storage keys, signed URLs, retention status",
    complianceControl: "Encryption, signed URLs, retention policy, access logging",
    lastChecked: "Jul 18 2026 at 5:32 PM ET",
    owner: "Super Admin",
    nextAction: "Bind encrypted object storage and signed evidence access URLs.",
  },
  {
    id: "INT-2607-0004",
    provider: "Malware scanning service",
    serviceArea: "Document validation",
    status: "Provider integration pending",
    environment: "Validation status modeled",
    dataAccess: "Uploaded file hash, file type, scan result, quarantine result",
    complianceControl: "Upload validation, malware scan, quarantine, replacement upload",
    lastChecked: "Jul 18 2026 at 5:33 PM ET",
    owner: "Administrator",
    nextAction: "Connect scanner callback to validation queue and quarantine controls.",
  },
  {
    id: "INT-2607-0005",
    provider: "Payment and accounting provider",
    serviceArea: "Client billing and notary payables",
    status: "Provider selection pending",
    environment: "Ledger controls modeled",
    dataAccess: "Invoice status, payable status, ledger corrections, tax onboarding",
    complianceControl: "Financial approval, W-9 restriction, ledger correction audit",
    lastChecked: "Jul 18 2026 at 5:34 PM ET",
    owner: "Super Admin",
    nextAction: "Select provider and bind ledger exports to financial approval receipts.",
  },
] as const;

export function findOrderRecord(orderId: string) {
  return orderRecords.find(
    (order) => order.id.toLowerCase() === orderId.toLowerCase(),
  );
}

export function findOrderOperationRecord(orderId: string) {
  return orderOperationRecords.find(
    (order) => order.id.toLowerCase() === orderId.toLowerCase(),
  );
}

export function documentsForOrder(orderId: string) {
  return documentRecords.filter(
    (document) => document.order.toLowerCase() === orderId.toLowerCase(),
  );
}

export function lifecycleForOrder(orderId: string) {
  return orderLifecycleRecords.filter(
    (stage) => stage.orderId.toLowerCase() === orderId.toLowerCase(),
  );
}

export function completionControlsForOrder(orderId: string) {
  return orderCompletionRecords.filter(
    (control) => control.orderId.toLowerCase() === orderId.toLowerCase(),
  );
}
